services:
  stripe:
    build:
      dockerfile: $PWD/Dockerfile-stubby
    ports:
      - "8002:8882"
    volumes:
      - $PWD/mocks/stripe.yml:/app/mock.yml

  braintree:
    build:
      dockerfile: $PWD/Dockerfile-stubby
    ports:
      - "8001:8882"
    volumes:
      - $PWD/mocks/braintree.yml:/app/mock.yml
