services:
  api-gateway:
    build:
      dockerfile: $PWD/Dockerfile
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      BRAINTREE_URL: stripe
      STRIPE_URL: braintree
    depends_on:
      - stripe
      - braintree

  stripe:
    build:
      dockerfile: $PWD/Dockerfile-stubby
    ports:
      - "8002:8882"
    environment:
      PORT: 8882
    volumes:
      - $PWD/mocks/stripe.yml:/app/mock.yml

  braintree:
    build:
      dockerfile: $PWD/Dockerfile-stubby
    ports:
      - "8001:8882"
    environment:
      PORT: 8882
    volumes:
      - $PWD/mocks/braintree.yml:/app/mock.yml
